const books = [
  {
    id: 1,
    title: 'Wings of Fire',
    author: 'A.P.J. Abdul Kalam',
    category: 'biography',
    price: 299,
    originalPrice: 499,
    rating: 4.8,
    reviews: 2341,
    image: 'assests/image/Wings of Fire.jpg',
    description: "Autobiography of India's beloved former president.",
    inStock: true,
  },
  {
    id: 2,
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    category: 'fiction',
    price: 349,
    originalPrice: 499,
    rating: 4.7,
    reviews: 5012,
    image: 'assests/image/The Alchemist.jpg',
    description: 'A magical story about pursuing your dreams.',
    inStock: true,
  },
  {
    id: 3,
    title: 'Atomic Habits',
    author: 'James Clear',
    category: 'self-help',
    price: 499,
    originalPrice: 799,
    rating: 4.9,
    reviews: 8420,
    image: 'assests/image/Atomic Habits.jpg',
    description: 'Tiny changes, remarkable results.',
    inStock: true,
  },
  {
    id: 4,
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    category: 'history',
    price: 599,
    originalPrice: 899,
    rating: 4.6,
    reviews: 12450,
    image: 'assests/image/Sapiens.jpg',
    description: 'A brief history of humankind.',
    inStock: true,
  },
  {
    id: 5,
    title: 'Rich Dad Poor Dad',
    author: 'Robert Kiyosaki',
    category: 'business',
    price: 350,
    originalPrice: 499,
    rating: 4.5,
    reviews: 6800,
    image: 'assests/image/Rich Dad Poor Dad.jpg',
    description: 'What the rich teach their kids about money.',
    inStock: true,
  },
  {
    id: 6,
    title: 'Five Point Someone',
    author: 'Chetan Bhagat',
    category: 'fiction',
    price: 199,
    originalPrice: 299,
    rating: 4.3,
    reviews: 9200,
    image: 'assests/image/Five Point Someone.jpg',
    description: 'What not to do at IIT.',
    inStock: false,
  },
  {
    id: 7,
    title: 'The Power of Subconscious Mind',
    author: 'Joseph Murphy',
    category: 'self-help',
    price: 249,
    originalPrice: 399,
    rating: 4.6,
    reviews: 4100,
    image: 'assests/image/The Power of Subconscious Mind.jpg',
    description: 'Unlock the power within you.',
    inStock: true,
  },
  {
    id: 8,
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    category: 'business',
    price: 299,
    originalPrice: 499,
    rating: 4.7,
    reviews: 7300,
    image: 'assests/image/Think and Grow Rich.jpg',
    description: 'The classic guide to success.',
    inStock: true,
  },
  {
    id: 9,
    title: 'Ikigai',
    author: 'Héctor García & Francesc Miralles',
    category: 'self-help',
    price: 399,
    originalPrice: 599,
    rating: 4.4,
    reviews: 3200,
    image: 'assests/image/Ikigai.jpg',
    description: 'The Japanese secret to a long and happy life.',
    inStock: true,
  },
  {
    id: 10,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    category: 'fiction',
    price: 249,
    originalPrice: 399,
    rating: 4.5,
    reviews: 4100,
    image: 'assests/image/The Great Gatsby.jpg',
    description: 'A story of decadence, idealism, and excess.',
    inStock: true,
  },
  {
    id: 11,
    title: 'Educated',
    author: 'Tara Westover',
    category: 'biography',
    price: 499,
    originalPrice: 699,
    rating: 4.7,
    reviews: 5600,
    image: 'assests/image/Educated.jpg',
    description: 'A memoir of a woman who leaves her survivalist family.',
    inStock: true,
  },
  {
    id: 12,
    title: 'Zero to One',
    author: 'Peter Thiel',
    category: 'business',
    price: 399,
    originalPrice: 599,
    rating: 4.6,
    reviews: 4800,
    image: 'assests/image/Zero to One.jpg',
    description: 'Notes on startups, or how to build the future.',
    inStock: true,
  },
  {
    id: 13,
    title: 'Same As Ever',
    author: 'Morgan Housel',
    category: 'self-help',
    price: 499,
    originalPrice: 699,
    rating: 4.8,
    reviews: 4200,
    image: 'assests/image/SAME AS EVER.jpg',
    description:
      'Timeless lessons on risk, opportunity, and living a good life.',
    inStock: true,
  },

  {
    id: 14,
    title: 'Deep Work',
    author: 'Cal Newport',
    category: 'self-help',
    price: 449,
    originalPrice: 649,
    rating: 4.7,
    reviews: 8500,
    image: 'assests/image/DEEP WORK.jpg',
    description: 'Rules for focused success in a distracted world.',
    inStock: true,
  },

  {
    id: 15,
    title: 'The Art of Letting Go',
    author: 'Nick Trenton',
    category: 'self-help',
    price: 399,
    originalPrice: 599,
    rating: 4.5,
    reviews: 1800,
    image: 'assests/image/The Art of Letting Go.jpg',
    description:
      'Move beyond the hurt, find emotional freedom, and restore your inner peace.',
    inStock: true,
  },

  {
    id: 16,
    title: 'स्टॉप ओव्हरथिंकिंग (Stop Overthinking)',
    author: 'Nick Trenton',
    category: 'self-help',
    price: 299,
    originalPrice: 499,
    rating: 4.4,
    reviews: 1200,
    image: 'assests/image/Stop Overthinking.jpg',
    description: 'अतिविचाराच्या चक्रातून बाहेर पडण्यासाठी मार्गदर्शक पुस्तक.',
    inStock: true,
  },

  {
    id: 17,
    title: 'You Can (Marathi)',
    author: 'George Matthew Adams',
    category: 'self-help',
    price: 249,
    originalPrice: 399,
    rating: 4.3,
    reviews: 950,
    image: 'assests/image/You Can.jpg',
    description:
      'यश, आत्मविश्वास आणि सकारात्मक विचारांवर आधारित प्रेरणादायी पुस्तक.',
    inStock: true,
  },

  {
    id: 18,
    title: 'The Secret (Marathi)',
    author: 'Rhonda Byrne',
    category: 'self-help',
    price: 349,
    originalPrice: 549,
    rating: 4.6,
    reviews: 6700,
    image: 'assests/image/The Secret.jpg',
    description: 'आकर्षणाच्या नियमाद्वारे जीवनात यश आणि आनंद मिळवण्याचे रहस्य.',
    inStock: true,
  },

  {
    id: 19,
    title: 'The Art of Letting Go',
    author: 'Nick Trenton',
    category: 'self-help',
    price: 449,
    originalPrice: 649,
    rating: 4.6,
    reviews: 2200,
    image: 'assests/image/The Art of Letting Go.jpg',
    description:
      'A practical guide to emotional healing, freedom, and personal growth.',
    inStock: true,
  },

  {
    id: 20,
    title: 'Can We Be Strangers Again?',
    author: 'Shrijeet Shandilya',
    category: 'fiction',
    price: 299,
    originalPrice: 499,
    rating: 4.5,
    reviews: 1400,
    image: 'assests/image/Can We be Strangers Again.jpg',
    description: 'A heartfelt story about love, heartbreak, and moving on.',
    inStock: true,
  },
];

console.log(`Loaded ${books.length} books`);
